#!/bin/bash

cd /var/tilde/

git pull

cp -f /var/tilde/db* /etc/bind/

cp -f /var/tilde/named.conf.* /etc/bind/

cp -f /var/tilde/named.conf /etc/bind/

cp -f /var/tilde/update_dns_zones_ubuntu /etc/bind/

systemctl reload bind9
